# They activate the theme and tell Jekyll to find your homepage content
# in /_sections. Note where "sections" starts with an underscore
# and where it doesn't. The social settings will make links to
# Twitter, etc., but only if you give the URL.
#
# Also, be sure to customize url and baseurl for your site.
#
# ---------------------------------------------------------------
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Nilearn Dev Days 2020"
subtitle: 
description: >- # this means to ignore newlines until "baseurl:"
        Join online the Nilearn development community and shape what's next
author: Nilearn team
email: nilearn.events@gmail.com
avatar: assets/images/avatar.jpg


# You'll want to customize url and baseurl for your own site:
baseurl: "/dev-days-2020" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe
#twitter_url:
#facebook_url:
#googleplus_url:
#instagram_url:
#linkedin_url:
#github_url:
#stackoverflow_url:
#pinterest_url:
#slack_url:
#dribbble_url:

# Google Analytics Tracking ID goes here:
#google_analytics:

# The following settings are NECESSARY for the Prologue theme to run:
remote_theme: chrisbobbe/jekyll-theme-prologue 
collections: [sections]
